name: "Developer Agreement"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  agreement:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read and agree to the Twitter Developer Agreement and Policy') || github.event_name == 'pull_request_target'
        uses: cla-assistant/github-action@ba066dbae3769e2ce93ec8cfc4fdc51b9db628ba #v2.1.3-beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN : ${{ secrets.CLA_PAT }}
        with:
          remote-organization-name: twitter
          remote-repository-name: .github-private
          path-to-signatures: 'developer-agreement/signatures.json'
          custom-pr-sign-comment: 'I have read and agree to the Twitter Developer Agreement and Policy'
          custom-notsigned-prcomment: '<br/>Thank you for your submission, we really appreciate it. We ask that you agree to the [Twitter Developer Agreement and Policy](https://developer.twitter.com/en/developer-terms/agreement-and-policy) before we can accept your proposal. You can agree by posting a comment with the following text:<br/>'
          custom-allsigned-prcomment: 'All contributors have signed the Developer Agreement. If the commit check is not passing, a maintainer must go the Checks tab of this PR and rerun the GitHub Action.'
          lock-pullrequest-aftermerge: false
          branch: 'main'
